# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/share/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /usr/share/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/capi1500/Documents/projekty/CoopShooter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/capi1500/Documents/projekty/CoopShooter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/share/clion/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/share/clion/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/share/clion/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/share/clion/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/share/clion/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/share/clion/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/share/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/share/clion/bin/cmake/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/share/clion/bin/cmake/bin/cpack --config ./CPackSourceConfig.cmake /home/capi1500/Documents/projekty/CoopShooter/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/share/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/capi1500/Documents/projekty/CoopShooter/CMakeFiles /home/capi1500/Documents/projekty/CoopShooter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/capi1500/Documents/projekty/CoopShooter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CoopShooter

# Build rule for target.
CoopShooter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CoopShooter
.PHONY : CoopShooter

# fast build rule for target.
CoopShooter/fast:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/build
.PHONY : CoopShooter/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/main.cpp.s
.PHONY : main.cpp.s

src/Bullet/bullet.o: src/Bullet/bullet.cpp.o

.PHONY : src/Bullet/bullet.o

# target to build an object file
src/Bullet/bullet.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Bullet/bullet.cpp.o
.PHONY : src/Bullet/bullet.cpp.o

src/Bullet/bullet.i: src/Bullet/bullet.cpp.i

.PHONY : src/Bullet/bullet.i

# target to preprocess a source file
src/Bullet/bullet.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Bullet/bullet.cpp.i
.PHONY : src/Bullet/bullet.cpp.i

src/Bullet/bullet.s: src/Bullet/bullet.cpp.s

.PHONY : src/Bullet/bullet.s

# target to generate assembly for a file
src/Bullet/bullet.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Bullet/bullet.cpp.s
.PHONY : src/Bullet/bullet.cpp.s

src/ContactListener/contactListener.o: src/ContactListener/contactListener.cpp.o

.PHONY : src/ContactListener/contactListener.o

# target to build an object file
src/ContactListener/contactListener.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/ContactListener/contactListener.cpp.o
.PHONY : src/ContactListener/contactListener.cpp.o

src/ContactListener/contactListener.i: src/ContactListener/contactListener.cpp.i

.PHONY : src/ContactListener/contactListener.i

# target to preprocess a source file
src/ContactListener/contactListener.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/ContactListener/contactListener.cpp.i
.PHONY : src/ContactListener/contactListener.cpp.i

src/ContactListener/contactListener.s: src/ContactListener/contactListener.cpp.s

.PHONY : src/ContactListener/contactListener.s

# target to generate assembly for a file
src/ContactListener/contactListener.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/ContactListener/contactListener.cpp.s
.PHONY : src/ContactListener/contactListener.cpp.s

src/Entity/entity.o: src/Entity/entity.cpp.o

.PHONY : src/Entity/entity.o

# target to build an object file
src/Entity/entity.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Entity/entity.cpp.o
.PHONY : src/Entity/entity.cpp.o

src/Entity/entity.i: src/Entity/entity.cpp.i

.PHONY : src/Entity/entity.i

# target to preprocess a source file
src/Entity/entity.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Entity/entity.cpp.i
.PHONY : src/Entity/entity.cpp.i

src/Entity/entity.s: src/Entity/entity.cpp.s

.PHONY : src/Entity/entity.s

# target to generate assembly for a file
src/Entity/entity.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Entity/entity.cpp.s
.PHONY : src/Entity/entity.cpp.s

src/Equipment/equipment.o: src/Equipment/equipment.cpp.o

.PHONY : src/Equipment/equipment.o

# target to build an object file
src/Equipment/equipment.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Equipment/equipment.cpp.o
.PHONY : src/Equipment/equipment.cpp.o

src/Equipment/equipment.i: src/Equipment/equipment.cpp.i

.PHONY : src/Equipment/equipment.i

# target to preprocess a source file
src/Equipment/equipment.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Equipment/equipment.cpp.i
.PHONY : src/Equipment/equipment.cpp.i

src/Equipment/equipment.s: src/Equipment/equipment.cpp.s

.PHONY : src/Equipment/equipment.s

# target to generate assembly for a file
src/Equipment/equipment.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Equipment/equipment.cpp.s
.PHONY : src/Equipment/equipment.cpp.s

src/Event/event.o: src/Event/event.cpp.o

.PHONY : src/Event/event.o

# target to build an object file
src/Event/event.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Event/event.cpp.o
.PHONY : src/Event/event.cpp.o

src/Event/event.i: src/Event/event.cpp.i

.PHONY : src/Event/event.i

# target to preprocess a source file
src/Event/event.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Event/event.cpp.i
.PHONY : src/Event/event.cpp.i

src/Event/event.s: src/Event/event.cpp.s

.PHONY : src/Event/event.s

# target to generate assembly for a file
src/Event/event.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Event/event.cpp.s
.PHONY : src/Event/event.cpp.s

src/EventManager/eventManager.o: src/EventManager/eventManager.cpp.o

.PHONY : src/EventManager/eventManager.o

# target to build an object file
src/EventManager/eventManager.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/EventManager/eventManager.cpp.o
.PHONY : src/EventManager/eventManager.cpp.o

src/EventManager/eventManager.i: src/EventManager/eventManager.cpp.i

.PHONY : src/EventManager/eventManager.i

# target to preprocess a source file
src/EventManager/eventManager.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/EventManager/eventManager.cpp.i
.PHONY : src/EventManager/eventManager.cpp.i

src/EventManager/eventManager.s: src/EventManager/eventManager.cpp.s

.PHONY : src/EventManager/eventManager.s

# target to generate assembly for a file
src/EventManager/eventManager.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/EventManager/eventManager.cpp.s
.PHONY : src/EventManager/eventManager.cpp.s

src/Game/game.o: src/Game/game.cpp.o

.PHONY : src/Game/game.o

# target to build an object file
src/Game/game.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Game/game.cpp.o
.PHONY : src/Game/game.cpp.o

src/Game/game.i: src/Game/game.cpp.i

.PHONY : src/Game/game.i

# target to preprocess a source file
src/Game/game.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Game/game.cpp.i
.PHONY : src/Game/game.cpp.i

src/Game/game.s: src/Game/game.cpp.s

.PHONY : src/Game/game.s

# target to generate assembly for a file
src/Game/game.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Game/game.cpp.s
.PHONY : src/Game/game.cpp.s

src/Item/item.o: src/Item/item.cpp.o

.PHONY : src/Item/item.o

# target to build an object file
src/Item/item.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Item/item.cpp.o
.PHONY : src/Item/item.cpp.o

src/Item/item.i: src/Item/item.cpp.i

.PHONY : src/Item/item.i

# target to preprocess a source file
src/Item/item.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Item/item.cpp.i
.PHONY : src/Item/item.cpp.i

src/Item/item.s: src/Item/item.cpp.s

.PHONY : src/Item/item.s

# target to generate assembly for a file
src/Item/item.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Item/item.cpp.s
.PHONY : src/Item/item.cpp.s

src/ItemManager/itemManager.o: src/ItemManager/itemManager.cpp.o

.PHONY : src/ItemManager/itemManager.o

# target to build an object file
src/ItemManager/itemManager.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/ItemManager/itemManager.cpp.o
.PHONY : src/ItemManager/itemManager.cpp.o

src/ItemManager/itemManager.i: src/ItemManager/itemManager.cpp.i

.PHONY : src/ItemManager/itemManager.i

# target to preprocess a source file
src/ItemManager/itemManager.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/ItemManager/itemManager.cpp.i
.PHONY : src/ItemManager/itemManager.cpp.i

src/ItemManager/itemManager.s: src/ItemManager/itemManager.cpp.s

.PHONY : src/ItemManager/itemManager.s

# target to generate assembly for a file
src/ItemManager/itemManager.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/ItemManager/itemManager.cpp.s
.PHONY : src/ItemManager/itemManager.cpp.s

src/Loader/loader.o: src/Loader/loader.cpp.o

.PHONY : src/Loader/loader.o

# target to build an object file
src/Loader/loader.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Loader/loader.cpp.o
.PHONY : src/Loader/loader.cpp.o

src/Loader/loader.i: src/Loader/loader.cpp.i

.PHONY : src/Loader/loader.i

# target to preprocess a source file
src/Loader/loader.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Loader/loader.cpp.i
.PHONY : src/Loader/loader.cpp.i

src/Loader/loader.s: src/Loader/loader.cpp.s

.PHONY : src/Loader/loader.s

# target to generate assembly for a file
src/Loader/loader.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Loader/loader.cpp.s
.PHONY : src/Loader/loader.cpp.s

src/Object/object.o: src/Object/object.cpp.o

.PHONY : src/Object/object.o

# target to build an object file
src/Object/object.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Object/object.cpp.o
.PHONY : src/Object/object.cpp.o

src/Object/object.i: src/Object/object.cpp.i

.PHONY : src/Object/object.i

# target to preprocess a source file
src/Object/object.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Object/object.cpp.i
.PHONY : src/Object/object.cpp.i

src/Object/object.s: src/Object/object.cpp.s

.PHONY : src/Object/object.s

# target to generate assembly for a file
src/Object/object.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Object/object.cpp.s
.PHONY : src/Object/object.cpp.s

src/PhysicObject/physicObject.o: src/PhysicObject/physicObject.cpp.o

.PHONY : src/PhysicObject/physicObject.o

# target to build an object file
src/PhysicObject/physicObject.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/PhysicObject/physicObject.cpp.o
.PHONY : src/PhysicObject/physicObject.cpp.o

src/PhysicObject/physicObject.i: src/PhysicObject/physicObject.cpp.i

.PHONY : src/PhysicObject/physicObject.i

# target to preprocess a source file
src/PhysicObject/physicObject.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/PhysicObject/physicObject.cpp.i
.PHONY : src/PhysicObject/physicObject.cpp.i

src/PhysicObject/physicObject.s: src/PhysicObject/physicObject.cpp.s

.PHONY : src/PhysicObject/physicObject.s

# target to generate assembly for a file
src/PhysicObject/physicObject.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/PhysicObject/physicObject.cpp.s
.PHONY : src/PhysicObject/physicObject.cpp.s

src/Player/player.o: src/Player/player.cpp.o

.PHONY : src/Player/player.o

# target to build an object file
src/Player/player.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Player/player.cpp.o
.PHONY : src/Player/player.cpp.o

src/Player/player.i: src/Player/player.cpp.i

.PHONY : src/Player/player.i

# target to preprocess a source file
src/Player/player.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Player/player.cpp.i
.PHONY : src/Player/player.cpp.i

src/Player/player.s: src/Player/player.cpp.s

.PHONY : src/Player/player.s

# target to generate assembly for a file
src/Player/player.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Player/player.cpp.s
.PHONY : src/Player/player.cpp.s

src/Sound/sound.o: src/Sound/sound.cpp.o

.PHONY : src/Sound/sound.o

# target to build an object file
src/Sound/sound.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Sound/sound.cpp.o
.PHONY : src/Sound/sound.cpp.o

src/Sound/sound.i: src/Sound/sound.cpp.i

.PHONY : src/Sound/sound.i

# target to preprocess a source file
src/Sound/sound.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Sound/sound.cpp.i
.PHONY : src/Sound/sound.cpp.i

src/Sound/sound.s: src/Sound/sound.cpp.s

.PHONY : src/Sound/sound.s

# target to generate assembly for a file
src/Sound/sound.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Sound/sound.cpp.s
.PHONY : src/Sound/sound.cpp.s

src/SoundManager/soundManager.o: src/SoundManager/soundManager.cpp.o

.PHONY : src/SoundManager/soundManager.o

# target to build an object file
src/SoundManager/soundManager.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/SoundManager/soundManager.cpp.o
.PHONY : src/SoundManager/soundManager.cpp.o

src/SoundManager/soundManager.i: src/SoundManager/soundManager.cpp.i

.PHONY : src/SoundManager/soundManager.i

# target to preprocess a source file
src/SoundManager/soundManager.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/SoundManager/soundManager.cpp.i
.PHONY : src/SoundManager/soundManager.cpp.i

src/SoundManager/soundManager.s: src/SoundManager/soundManager.cpp.s

.PHONY : src/SoundManager/soundManager.s

# target to generate assembly for a file
src/SoundManager/soundManager.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/SoundManager/soundManager.cpp.s
.PHONY : src/SoundManager/soundManager.cpp.s

src/TextureManager/textureManager.o: src/TextureManager/textureManager.cpp.o

.PHONY : src/TextureManager/textureManager.o

# target to build an object file
src/TextureManager/textureManager.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/TextureManager/textureManager.cpp.o
.PHONY : src/TextureManager/textureManager.cpp.o

src/TextureManager/textureManager.i: src/TextureManager/textureManager.cpp.i

.PHONY : src/TextureManager/textureManager.i

# target to preprocess a source file
src/TextureManager/textureManager.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/TextureManager/textureManager.cpp.i
.PHONY : src/TextureManager/textureManager.cpp.i

src/TextureManager/textureManager.s: src/TextureManager/textureManager.cpp.s

.PHONY : src/TextureManager/textureManager.s

# target to generate assembly for a file
src/TextureManager/textureManager.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/TextureManager/textureManager.cpp.s
.PHONY : src/TextureManager/textureManager.cpp.s

src/Weapon/weapon.o: src/Weapon/weapon.cpp.o

.PHONY : src/Weapon/weapon.o

# target to build an object file
src/Weapon/weapon.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Weapon/weapon.cpp.o
.PHONY : src/Weapon/weapon.cpp.o

src/Weapon/weapon.i: src/Weapon/weapon.cpp.i

.PHONY : src/Weapon/weapon.i

# target to preprocess a source file
src/Weapon/weapon.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Weapon/weapon.cpp.i
.PHONY : src/Weapon/weapon.cpp.i

src/Weapon/weapon.s: src/Weapon/weapon.cpp.s

.PHONY : src/Weapon/weapon.s

# target to generate assembly for a file
src/Weapon/weapon.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/Weapon/weapon.cpp.s
.PHONY : src/Weapon/weapon.cpp.s

src/World/world.o: src/World/world.cpp.o

.PHONY : src/World/world.o

# target to build an object file
src/World/world.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/World/world.cpp.o
.PHONY : src/World/world.cpp.o

src/World/world.i: src/World/world.cpp.i

.PHONY : src/World/world.i

# target to preprocess a source file
src/World/world.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/World/world.cpp.i
.PHONY : src/World/world.cpp.i

src/World/world.s: src/World/world.cpp.s

.PHONY : src/World/world.s

# target to generate assembly for a file
src/World/world.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/World/world.cpp.s
.PHONY : src/World/world.cpp.s

src/WorldObject/worldObject.o: src/WorldObject/worldObject.cpp.o

.PHONY : src/WorldObject/worldObject.o

# target to build an object file
src/WorldObject/worldObject.cpp.o:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/WorldObject/worldObject.cpp.o
.PHONY : src/WorldObject/worldObject.cpp.o

src/WorldObject/worldObject.i: src/WorldObject/worldObject.cpp.i

.PHONY : src/WorldObject/worldObject.i

# target to preprocess a source file
src/WorldObject/worldObject.cpp.i:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/WorldObject/worldObject.cpp.i
.PHONY : src/WorldObject/worldObject.cpp.i

src/WorldObject/worldObject.s: src/WorldObject/worldObject.cpp.s

.PHONY : src/WorldObject/worldObject.s

# target to generate assembly for a file
src/WorldObject/worldObject.cpp.s:
	$(MAKE) -f CMakeFiles/CoopShooter.dir/build.make CMakeFiles/CoopShooter.dir/src/WorldObject/worldObject.cpp.s
.PHONY : src/WorldObject/worldObject.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... CoopShooter"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Bullet/bullet.o"
	@echo "... src/Bullet/bullet.i"
	@echo "... src/Bullet/bullet.s"
	@echo "... src/ContactListener/contactListener.o"
	@echo "... src/ContactListener/contactListener.i"
	@echo "... src/ContactListener/contactListener.s"
	@echo "... src/Entity/entity.o"
	@echo "... src/Entity/entity.i"
	@echo "... src/Entity/entity.s"
	@echo "... src/Equipment/equipment.o"
	@echo "... src/Equipment/equipment.i"
	@echo "... src/Equipment/equipment.s"
	@echo "... src/Event/event.o"
	@echo "... src/Event/event.i"
	@echo "... src/Event/event.s"
	@echo "... src/EventManager/eventManager.o"
	@echo "... src/EventManager/eventManager.i"
	@echo "... src/EventManager/eventManager.s"
	@echo "... src/Game/game.o"
	@echo "... src/Game/game.i"
	@echo "... src/Game/game.s"
	@echo "... src/Item/item.o"
	@echo "... src/Item/item.i"
	@echo "... src/Item/item.s"
	@echo "... src/ItemManager/itemManager.o"
	@echo "... src/ItemManager/itemManager.i"
	@echo "... src/ItemManager/itemManager.s"
	@echo "... src/Loader/loader.o"
	@echo "... src/Loader/loader.i"
	@echo "... src/Loader/loader.s"
	@echo "... src/Object/object.o"
	@echo "... src/Object/object.i"
	@echo "... src/Object/object.s"
	@echo "... src/PhysicObject/physicObject.o"
	@echo "... src/PhysicObject/physicObject.i"
	@echo "... src/PhysicObject/physicObject.s"
	@echo "... src/Player/player.o"
	@echo "... src/Player/player.i"
	@echo "... src/Player/player.s"
	@echo "... src/Sound/sound.o"
	@echo "... src/Sound/sound.i"
	@echo "... src/Sound/sound.s"
	@echo "... src/SoundManager/soundManager.o"
	@echo "... src/SoundManager/soundManager.i"
	@echo "... src/SoundManager/soundManager.s"
	@echo "... src/TextureManager/textureManager.o"
	@echo "... src/TextureManager/textureManager.i"
	@echo "... src/TextureManager/textureManager.s"
	@echo "... src/Weapon/weapon.o"
	@echo "... src/Weapon/weapon.i"
	@echo "... src/Weapon/weapon.s"
	@echo "... src/World/world.o"
	@echo "... src/World/world.i"
	@echo "... src/World/world.s"
	@echo "... src/WorldObject/worldObject.o"
	@echo "... src/WorldObject/worldObject.i"
	@echo "... src/WorldObject/worldObject.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

